name: 'bomberos_dw'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
vars:
  reprocess_days: 7

models:
  bomberos_dw:
    +meta:
      pii_status: masked       # todos los modelos tienen PII suprimida o tokenizada
      project: bomberos_dw

    staging:
      +materialized: view
      +schema: silver
      +tags:
        - silver
        - staging
      +meta:
        layer: silver
        criticality: medium

    marts:
      +materialized: table
      +schema: gold
      +tags:
        - gold
      +meta:
        layer: gold
        criticality: high
        refresh_frequency: daily